#!/usr/bin/env python3
"""Batch translation helper for large markdown files."""

import re

# Translation mappings for common terms and phrases
TRANSLATIONS = {
    # File 1: COMPLETE_PIPELINE_SIMULATION.md
    "步骤": "Step",
    "断点": "Checkpoint",
    "生成": "Generate/Generation",
    "剩余数据": "remaining data",
    "合并数据": "merge data",
    "处理": "Process",
    "样本": "sample(s)",
    "系统输出": "System Output",
    "系统继续输出": "System Continues Output",
    "用户输入": "User Input",
    "加载了": "Loaded",
    "条原始数据": "original data samples",
    "输出文件": "Output file",
    "处理数据": "Processing data",
    "完成": "Complete",
    "输出": "Output",
    "加载数据": "Loading data",
    "原始": "Original",
    "改写": "Rephrased",
    "对比": "Comparison",
    "请仔细查看原始数据与改写数据": "Please carefully review original vs rephrased data",
    "请输入不合格样本的序号": "Enter the sample numbers that are unqualified",
    "多个序号用逗号分隔": "separated by commas",
    "示例": "Example",
    "表示": "means",
    "个样本不合格": "samples are unqualified",
    "如果全部合格，直接按回车": "If all are qualified, press Enter directly",
    "不合格样本序号": "Unqualified sample numbers",
    "统计": "Statistics",
    "合格样本": "Qualified samples",
    "不合格样本": "Unqualified samples",
    "执行": "Performing/Execute",
    "使用原始数据": "Using original data",
    "不合格": "unqualified",
    "替换被拒绝的样本": "replaced rejected samples",
    "保存结果": "Saving results",
    "已保存": "Saved",
    "生成了": "Generated",
    "注入": "Injecting/Injected",
    "备份已保存": "Backup saved",
    "下一步": "Next step",
    "运行": "Run",
    "数据集特点": "Dataset Characteristics",
    "任务类型": "Task Type",
    "改写字段": "Field to Rephrase",
    "其他字段": "Other Fields",
    "配置文件关键修改": "Key Configuration Modifications",
    "流程与": "The workflow is the same as",
    "完全相同": "completely the same",
    "只是字段名从": "except the field name changes from",
    "变为": "to",
    "样本对比示例": "Sample Comparison Examples",
    "特有": "specific",
    "使用场景": "Use Case",
    "已经通过": "After",
    "生成获得了": "generation obtained",
    "可用的": "usable",
    "现在想要快速探究": "now want to quickly explore",
    "不同": "different",
    "参数": "parameter(s)",
    "对合成数据质量的影响": "impact on synthetic data quality",
    "准备": "Prepare",
    "配置": "Configuration",
    "配置内容": "Configuration Content",
    "直接全量生成": "Direct full generation",
    "参数变量": "parameter variable",
    "必须包含完整的": "Must include complete",
    "从第一次": "from the first",
    "生成中获得": "generation obtained",
    "不需要": "doesn't need",
    "生成": "Generate",
    "个不同": "different",
    "的配置": "configurations",
    "生成并运行": "Generate and Run",
    "重复生成其他": "Repeat for other",
    "自动管理": "Automatic Management",
    "物理存储": "Physical Storage",
    "视图": "View",
    "符号链接": "symbolic link",
    "数据集对比表": "Dataset Comparison Table",
    "场景": "Scenario",
    "数据集": "Dataset",
    "模式": "Mode",
    "断点数": "Number of Checkpoints",
    "总耗时": "Total Time",
    "估算": "estimated",
    "人工参与时间对比": "Manual Participation Time Comparison",
    "审核": "Review",
    "浏览": "Browse",
    "输入序号": "Input numbers",
    "总计人工时间": "Total Manual Time",
    "无需人工参与": "No manual participation needed",
    "完全自动化，适合参数研究": "Fully automated, suitable for parameter studies",
    "关键要点总结": "Key Points Summary",
    "批量输入模式": "Batch Input Mode",
    "用户只需输入": "Users only need to input",
    "无需逐个确认": "No need to confirm one by one",
    "大幅减少人工交互时间": "Significantly reduces manual interaction time",
    "自动": "Automatic",
    "系统自动替换": "System automatically replaces",
    "为原始数据": "with original data",
    "所有": "all",
    "个断点": "checkpoints",
    "都执行": "all execute",
    "从": "from",
    "个合格样本": "qualified samples",
    "标注": "Annotation/Label",
    "由系统自动完成": "automatically completed by system",
    "用于测试": "used to test",
    "准确率": "accuracy",
    "多数据集零代码支持": "Zero-code Support for Multiple Datasets",
    "只需修改配置文件中的": "Only need to modify",
    "无需修改任何代码": "No code changes needed",
    "方案": "Solution",
    "自动检测相同参数配置": "Automatically detect same parameter configuration",
    "避免重复生成": "Avoid duplicate generation",
    "通过符号链接组织实验": "Organize experiments through symbolic links",
    "两种生成策略": "Two Generation Strategies",
    "探索性实验，需要确定": "Exploratory experiment, need to determine",
    "已确定，快速参数研究": "already determined, fast parameter study",
    "使用建议": "Usage Recommendations",
    "首次实验": "First experiment",
    "使用": "Use",
    "确定最佳": "determine best",
    "获得": "obtain",
    "后": "after",
    "快速生成不同参数配置的数据": "quickly generate data with different parameter configurations",
    "人工审核": "Manual review",
    "认真审核前": "Carefully review the first",
    "个样本": "samples",
    "确保": "ensure",
    "管理": "Management",
    "等工具查看和管理实验": "and other tools to view and manage experiments",
    "数据复用": "Data Reuse",
    "善用": "Make good use of",
    "系统的": "system's",
    "功能": "feature",

    # Additional common phrases
    "文档": "Document",
    "说明": "Explanation/Description",
    "如何": "How to",
    "支持": "Support",
    "包含": "Include/Contains",
    "必要的": "necessary",
    "验证": "Validation",
    "基于": "Based on",
    "已验证": "validated",
    "快速": "quick/fast",
    "调参": "parameter tuning",
    "复用": "reuse",
    "实现状态": "Implementation Status",
    "已实现工具": "Implemented Tools",
    "位置": "Location",
    "状态": "Status",
    "已实现": "Implemented",
    "已修复": "Fixed",
    "关键修复": "Key Fixes",
    "排除": "Exclude",
    "逻辑": "logic",
    "索引": "index",
    "这些样本用作": "These samples are used as",
    "的": "of/for",
    "不应被": "should not be",
    "避免数据泄露": "avoid data leakage",
    "修复位置": "Fix location",
    "直接使用合成数据": "directly use synthetic data",
    "不经过": "without",
    "重要说明": "Important Notes",
    "只合成": "Only synthesize",
    "会合成": "will synthesize",
    "训练数据": "training data",
    "数据直接从原始数据集复制": "data copied directly from original dataset",
    "合成数据": "synthetic data",
    "经过": "through/after",
    "原始数据": "original data",
    "从": "from",
    "复制": "copied",
    "这样做是为了": "This is to",
    "保持": "maintain",
    "标准化": "standardization",
    "保持原始状态": "maintain original state",
    "确保公平评估": "ensure fair evaluation",
    "实验结果可比较": "experiment results comparable",
    "不同实验使用相同的": "different experiments use the same",
    "符合研究惯例": "follows research conventions",
    "只在训练阶段使用": "only use in training phase",
    "增强": "augmentation/enhancement",
    "自动处理": "Automatic processing",
    "在验证": "After validating",
    "后": "after",
    "会自动从原始数据集复制": "will automatically copy from original dataset",
    "文件": "file(s)",
}

def print_translation_reference():
    """Print translation reference for manual use."""
    print("=" * 80)
    print("TRANSLATION REFERENCE FOR MANUAL EDITING")
    print("=" * 80)
    print("\nCommon Terms:")
    for cn, en in sorted(TRANSLATIONS.items())[:30]:
        print(f"  {cn:30s} -> {en}")
    print("\n... and many more (see TRANSLATIONS dict in script)\n")
    print("=" * 80)

if __name__ == "__main__":
    print_translation_reference()
    print("\nThis script provides translation reference.")
    print("Use the Edit tool manually for precise translations.")
