#!/usr/bin/env python3
"""
Script to translate Chinese text to English in archive markdown files.
"""

import re

# Translation dictionary for common terms and phrases
translations = {
    # Headers and sections
    "问题": "Issue",
    "严重问题": "Critical Issues",
    "必须修复": "Must Fix",
    "高优先级问题": "High Priority Issues",
    "中优先级问题": "Medium Priority Issues",
    "低优先级问题": "Low Priority Issues",
    "正确实现的功能": "Correctly Implemented Features",
    "修复优先级和路线图": "Fix Priority and Roadmap",
    "测试验证计划": "Test Validation Plan",
    "影响分析": "Impact Analysis",
    "建议": "Recommendations",
    "附录": "Appendix",
    "执行摘要": "Executive Summary",
    "关键发现": "Key Finding",

    # Common terms
    "文件": "File",
    "对应SIMULATION": "Related SIMULATION",
    "问题描述": "Issue Description",
    "根本原因": "Root Cause",
    "影响": "Impact",
    "修复方案": "Fix",
    "测试验证": "Test Validation",
    "关联影响": "Related Impact",
    "潜在问题": "Potential Issues",
    "实际案例": "Actual Example",
    "数据流错误": "Data Flow Error",
    "场景": "Scenario",
    "步骤": "Step",
    "行": "lines",

    # Status and severity
    "严重等级": "Severity Level",
    "数量": "Count",
    "完全阻塞pipeline运行": "Completely blocks pipeline execution",
    "显著影响用户体验和数据质量": "Significantly impacts user experience and data quality",
    "影响代码质量和可维护性": "Affects code quality and maintainability",
    "轻微问题": "Minor issues",
    "总计": "Total",

    # Error and warning messages
    "错误": "Wrong",
    "正确": "Correct",
    "错误：": "Wrong:",
    "正确：": "Correct:",
    "应该": "Should",
    "应该能找到": "Should find",
    "期望输出": "Expected output",
    "实际输出": "Actual output",
    "当前代码": "Current code",

    # Actions and recommendations
    "推荐": "Recommended",
    "方案": "Option",
    "备用": "Fallback",
    "修复后测试": "Test after fix",
    "紧急修复": "Emergency Fix",
    "质量改进": "Quality Improvement",
    "代码质量": "Code Quality",
    "时间估计": "Time Estimate",
    "目标": "Goal",
    "使two-stage pipeline可运行": "Make two-stage pipeline operational",
    "提升用户体验和数据质量": "Improve user experience and data quality",
    "提升代码质量和可维护性": "Improve code quality and maintainability",

    # Phase and priority
    "阶段": "Phase",
    "优先级": "Priority",
    "当前状态": "Current Status",
    "需要执行的迁移": "Required Migration",
    "完整流程测试": "Complete Workflow Test",
    "模式测试": "Mode Test",
    "去重测试": "Deduplication Test",

    # Specific technical terms
    "样本标注": "sample annotation",
    "阻塞整个": "blocks the entire",
    "流程的后半部分": "second half of the workflow",
    "用户会收到": "User receives",
    "从数据集子目录读取": "Read from dataset subdirectory",
    "直接从父目录读取": "Reading directly from parent directory",
    "数据文件实际存储在": "Data files are actually stored in",
    "数据集子目录": "dataset subdirectory",
    "生成": "generated by",
    "实际位置": "Actual location",
    "完全无法运行": "completely fails",
    "断点": "Checkpoint",

    # More common Chinese phrases
    "如果用户忘记合并": "If user forgets to merge",
    "会报错找不到文件": "fails with file not found error",
    "增加用户操作复杂度和出错概率": "Increases user operation complexity and error probability",
    "自动合并": "Auto-merge",
    "在生成": "when generating",
    "时": "when",
    "后添加": "Add after",
    "合并代码": "merge_code",
    "数据": "data",
    "复制": "Copy",
    "追加": "Append",
    "已自动合并": "Auto-merged",
    "未找到": "not found",
    "跳过合并": "skipping merge",
    "训练文件不存在": "Training file not found",
    "自动检测和合并": "Auto-detect and merge",
    "在": "In",
    "的数据加载部分": "data loading section",
    "尝试合并": "Try to merge",
    "执行合并逻辑": "Execute merge logic",

    # Issue 3 specific
    "生成的脚本缺少": "Generated script missing",
    "参数": "parameter",
    "没有": "No",
    "但配置文件明确指定了": "However, the config file explicitly specifies",
    "被忽略了": "Being ignored",
    "计算指纹时包含了": "includes",
    " in fingerprint calculation",
    "生成API调用时没有传递": "doesn't pass",
    " to API call",
    "导致": "Results in",
    "相同指纹的实验可能生成不同的数据": "experiments with same fingerprint potentially generating different data",
    "因为实际API参数不一致": "due to inconsistent actual API parameters",
    "机制失效": "mechanism fails",
    "相同指纹但不同": "same fingerprint but different",
    "会生成不同数据": "generates different data",
    "无法准确复现实验结果": "Cannot accurately reproduce experiment results",
    "实验": "experiments",
    "无法正确进行": "cannot proceed correctly",
    "添加": "Add",
    "和其他采样参数": "and other sampling parameters",
    "需要同步修复": "Need to synchronously fix",
    "的指纹计算": "fingerprint calculation in",
    "确保包含的参数与API调用一致": "to ensure included parameters match API calls",

    # More translations
    "统计逻辑错误": "Statistical logic error",
    "排除样本": "Exclude samples",
    "索引": "index",
    "不经过": "without going through",
    "验证": "validation",
    "计入通过数": "counted as passed",
    "计入总数": "counted in total",
    "包含了未验证的样本": "includes unvalidated samples",
    "被跳过验证": "skipped validation",
    "避免数据泄露": "avoid data leakage",
    "这是正确的": "this is correct",
    "但它们": "but they",
    "准确率统计不准确": "accuracy statistics are inaccurate",
    "准确率统计虚高": "accuracy statistics are inflated",
    "中": "in",
    "个样本无条件标记为": "samples unconditionally marked as",
    "通过": "passed",
    "用户无法准确评估": "User cannot accurately assess",
    "质量": "quality",
    "的输出与文档不符": "output doesn't match documentation",
    "期望输出": "Expected output",
    "总验证样本": "Total validation samples",
    "应该排除": "should exclude",
    "判断为": "Judged as",
    "相同": "same",
    "不相同": "not the same",
    "错误地包含了": "incorrectly includes",
    "虚高": "inflated",
    "在循环外单独统计": "Track separately outside loop",
    "单独统计": "Track separately",
    "不变": "unchanged",
    "如果": "if",
    "最终统计": "Final statistics",
    "验证完成": "Validation completed",
    "验证样本": "Validation samples",
    "排除了": "excluding",
    "和": "and",
    "跳过验证，直接使用": "skipped validation, directly used",
    "使用": "using",
    "条数据运行": "samples run",

    # Design flaw
    "生成的": "generated",
    "文件未被使用": "file not being used",
    "设计缺陷": "design flaw",
    "保存": "saves",
    "后的数据": "data after",
    "但后续流程使用的是": "but subsequent workflow uses",
    "读取": "reads",
    "未经": "without",
    "最终合并时也使用": "final merge also uses",
    "原始改写": "original rephrase",
    "被忽略": "ignored",
    "合并步骤使用": "Merge step uses",
    "完全失效": "completely ineffective",
    "不合格样本没有被替换为原始数据": "unqualified samples not replaced with original data",
    "最终训练数据包含不合格的改写样本": "final training data contains unqualified rephrased samples",
    "的": "of",
    "功能未实现": "functionality not implemented",
    "直接覆盖原文件": "Directly overwrite original file",
    "直接覆盖": "directly overwrite",
    "已覆盖原文件": "overwrote original file",
    "修改合并逻辑使用": "Modify merge logic to use",
    "版本": "version",
    "回退到原始文件": "fall back to original file",
}

def translate_text(text):
    """Translate Chinese text to English using the translations dictionary."""
    result = text
    for chinese, english in translations.items():
        result = result.replace(chinese, english)
    return result

def translate_file(input_file, output_file):
    """Translate Chinese content in a markdown file."""
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Translate the content
    translated = translate_text(content)

    # Write to output file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(translated)

    print(f"Translated {input_file} -> {output_file}")

if __name__ == "__main__":
    files = [
        "/home/ubuntu/LLM-inference/jikai-project/Synthetic_Data_for_ZO/archive/COMPLETE_CODE_REVIEW_REPORT.md",
        "/home/ubuntu/LLM-inference/jikai-project/Synthetic_Data_for_ZO/archive/COMPLETE_SYSTEM_SUMMARY.md",
        "/home/ubuntu/LLM-inference/jikai-project/Synthetic_Data_for_ZO/archive/DATA_REFERENCE.md",
    ]

    for file in files:
        translate_file(file, file)
